# The URL the site will be built for
base_url = "https://example.com"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

# Set Theme
theme="xyblag"

# Theme related variables
title="Machine Learning Bytes"
description=" My Portfolio and Notes on 🤖 "

# generate feed
generate_feed=true

# Taxonomies
taxonomies = [
    # You can enable/disable RSS
    {name = "categories", feed = true},
    {name = "tags", feed = true},
    {name = "blog", feed = true},
]

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true
highlight_theme = "charcoal"

# When set to "true", emoji aliases translated to their corresponding
# Unicode emoji equivalent in the rendered Markdown files. (e.g.: :smile: => 😄)
render_emoji = true

[extra]
author = "Akhil"
# Menu shown in the navbar
blog_menu = [
    {url = "$BASE_URL/blog", name = "Blog"},
    {url = "$BASE_URL/categories", name = "Categories"},
    {url = "$BASE_URL/tags", name = "Tags"},
    {url = "$BASE_URL/about", name = "About"},
]

[extra.social_links]
twitter = "https://twitter.com/143akhi"
github = "https://github.com/Enforcer007"
